import{S as f,a as c,i as u}from"./assets/vendor-30VqbI-A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const g=document.querySelector(".gallery"),i=document.querySelector(".gallery+span"),h=new f(".gallery li a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(a=>{const{webformatURL:n,tags:e,largeImageURL:t,likes:s,views:m,comments:d,downloads:p}=a;return`<li class="gallery-card">
          <a href="${t}">
            <img src="${n}" alt="${e}" class="card-image" width="360" height="152" />
            <ul class="card-caption">
              <li class="image-tag"><p>Likes<br />${s}</p></li>
              <li class="image-tag"><p>Views<br />${m}</p></li>
              <li class="image-tag"><p>Comments<br />${d}</p></li>
              <li class="image-tag"><p>Downloads<br />${p}</p></li>
            </ul>
          </a>
        </li>`}).join("");i.classList.toggle("loader"),g.insertAdjacentHTML("beforeend",r),h.refresh()}c.defaults.baseURL="https://pixabay.com/api/";const l={key:"49370503-7e4a3b73ee503433174e66c4b",image_type:"photo",orientation:"horizontal",per_page:9,safesearch:!0};function L(o,r){l.q=o,c.get(`?${new URLSearchParams(l)}`).then(a=>{if(a.data.totalHits===0){i.classList.toggle("loader"),b();return}r(a.data.hits)}).catch(()=>{i.classList.toggle("loader"),i.innerHTML="Oops... something went wrong..."})}function b(){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const w=document.querySelector(".form");w.addEventListener("submit",P);function P(o){o.preventDefault();const r=o.currentTarget.elements.search.value.toLowerCase().trim();if(!r){u.error({message:"Search field must not be empty!",position:"topRight"});return}g.innerHTML="",i.classList.toggle("loader"),L(r,y)}
//# sourceMappingURL=index.js.map
